"""Create initial tables

Revision ID: 32ce35e7e614
Revises: 
Create Date: 2025-09-23 11:40:14.956163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32ce35e7e614'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bet_combinations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('combination_type', sa.String(), nullable=False),
    sa.Column('selections_count', sa.Integer(), nullable=False),
    sa.Column('total_odds', sa.Float(), nullable=False),
    sa.Column('min_odds', sa.Float(), nullable=True),
    sa.Column('max_odds', sa.Float(), nullable=True),
    sa.Column('target_confidence', sa.Float(), nullable=True),
    sa.Column('combined_probability', sa.Float(), nullable=True),
    sa.Column('combined_confidence', sa.Float(), nullable=True),
    sa.Column('expected_value', sa.Float(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('prediction_ids', sa.JSON(), nullable=False),
    sa.Column('selection_details', sa.JSON(), nullable=True),
    sa.Column('is_recommended', sa.Boolean(), nullable=True),
    sa.Column('recommendation_reason', sa.Text(), nullable=True),
    sa.Column('risk_level', sa.String(), nullable=True),
    sa.Column('is_settled', sa.Boolean(), nullable=True),
    sa.Column('is_winner', sa.Boolean(), nullable=True),
    sa.Column('actual_return', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bet_combinations_id'), 'bet_combinations', ['id'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('short_name', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('league', sa.String(), nullable=True),
    sa.Column('founded', sa.Integer(), nullable=True),
    sa.Column('venue', sa.String(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('elo_rating', sa.Float(), nullable=True),
    sa.Column('form_rating', sa.Float(), nullable=True),
    sa.Column('attack_rating', sa.Float(), nullable=True),
    sa.Column('defense_rating', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_external_id'), 'teams', ['external_id'], unique=True)
    op.create_index(op.f('ix_teams_id'), 'teams', ['id'], unique=False)
    op.create_index(op.f('ix_teams_league'), 'teams', ['league'], unique=False)
    op.create_index(op.f('ix_teams_name'), 'teams', ['name'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('league', sa.String(), nullable=True),
    sa.Column('season', sa.String(), nullable=True),
    sa.Column('matchday', sa.Integer(), nullable=True),
    sa.Column('match_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('venue', sa.String(), nullable=True),
    sa.Column('referee', sa.String(), nullable=True),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('home_score_ht', sa.Integer(), nullable=True),
    sa.Column('away_score_ht', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('minute', sa.Integer(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('weather_condition', sa.String(), nullable=True),
    sa.Column('importance_factor', sa.Float(), nullable=True),
    sa.Column('motivation_home', sa.Float(), nullable=True),
    sa.Column('motivation_away', sa.Float(), nullable=True),
    sa.Column('is_predicted', sa.Boolean(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_external_id'), 'matches', ['external_id'], unique=True)
    op.create_index(op.f('ix_matches_id'), 'matches', ['id'], unique=False)
    op.create_index(op.f('ix_matches_league'), 'matches', ['league'], unique=False)
    op.create_index(op.f('ix_matches_match_date'), 'matches', ['match_date'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('nationality', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('jersey_number', sa.Integer(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('preferred_foot', sa.String(), nullable=True),
    sa.Column('market_value', sa.Float(), nullable=True),
    sa.Column('contract_until', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_injured', sa.Boolean(), nullable=True),
    sa.Column('is_suspended', sa.Boolean(), nullable=True),
    sa.Column('appearances_season', sa.Integer(), nullable=True),
    sa.Column('goals_season', sa.Integer(), nullable=True),
    sa.Column('assists_season', sa.Integer(), nullable=True),
    sa.Column('yellow_cards_season', sa.Integer(), nullable=True),
    sa.Column('red_cards_season', sa.Integer(), nullable=True),
    sa.Column('minutes_played_season', sa.Integer(), nullable=True),
    sa.Column('xg_season', sa.Float(), nullable=True),
    sa.Column('xa_season', sa.Float(), nullable=True),
    sa.Column('pass_completion_rate', sa.Float(), nullable=True),
    sa.Column('tackle_success_rate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_external_id'), 'players', ['external_id'], unique=True)
    op.create_index(op.f('ix_players_id'), 'players', ['id'], unique=False)
    op.create_table('team_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.String(), nullable=False),
    sa.Column('games_played', sa.Integer(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('draws', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('goals_for', sa.Integer(), nullable=True),
    sa.Column('goals_against', sa.Integer(), nullable=True),
    sa.Column('clean_sheets', sa.Integer(), nullable=True),
    sa.Column('avg_xg_for', sa.Float(), nullable=True),
    sa.Column('avg_xg_against', sa.Float(), nullable=True),
    sa.Column('avg_possession', sa.Float(), nullable=True),
    sa.Column('avg_shots_for', sa.Float(), nullable=True),
    sa.Column('avg_shots_against', sa.Float(), nullable=True),
    sa.Column('avg_corners_for', sa.Float(), nullable=True),
    sa.Column('avg_corners_against', sa.Float(), nullable=True),
    sa.Column('home_wins', sa.Integer(), nullable=True),
    sa.Column('home_draws', sa.Integer(), nullable=True),
    sa.Column('home_losses', sa.Integer(), nullable=True),
    sa.Column('away_wins', sa.Integer(), nullable=True),
    sa.Column('away_draws', sa.Integer(), nullable=True),
    sa.Column('away_losses', sa.Integer(), nullable=True),
    sa.Column('form_trend', sa.JSON(), nullable=True),
    sa.Column('goal_trend', sa.JSON(), nullable=True),
    sa.Column('xg_trend', sa.JSON(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_statistics_id'), 'team_statistics', ['id'], unique=False)
    op.create_table('match_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('possession_home', sa.Float(), nullable=True),
    sa.Column('possession_away', sa.Float(), nullable=True),
    sa.Column('shots_home', sa.Integer(), nullable=True),
    sa.Column('shots_away', sa.Integer(), nullable=True),
    sa.Column('shots_on_target_home', sa.Integer(), nullable=True),
    sa.Column('shots_on_target_away', sa.Integer(), nullable=True),
    sa.Column('corners_home', sa.Integer(), nullable=True),
    sa.Column('corners_away', sa.Integer(), nullable=True),
    sa.Column('fouls_home', sa.Integer(), nullable=True),
    sa.Column('fouls_away', sa.Integer(), nullable=True),
    sa.Column('yellow_cards_home', sa.Integer(), nullable=True),
    sa.Column('yellow_cards_away', sa.Integer(), nullable=True),
    sa.Column('red_cards_home', sa.Integer(), nullable=True),
    sa.Column('red_cards_away', sa.Integer(), nullable=True),
    sa.Column('xg_home', sa.Float(), nullable=True),
    sa.Column('xg_away', sa.Float(), nullable=True),
    sa.Column('xga_home', sa.Float(), nullable=True),
    sa.Column('xga_away', sa.Float(), nullable=True),
    sa.Column('passes_home', sa.Integer(), nullable=True),
    sa.Column('passes_away', sa.Integer(), nullable=True),
    sa.Column('pass_accuracy_home', sa.Float(), nullable=True),
    sa.Column('pass_accuracy_away', sa.Float(), nullable=True),
    sa.Column('progressive_passes_home', sa.Integer(), nullable=True),
    sa.Column('progressive_passes_away', sa.Integer(), nullable=True),
    sa.Column('tackles_home', sa.Integer(), nullable=True),
    sa.Column('tackles_away', sa.Integer(), nullable=True),
    sa.Column('interceptions_home', sa.Integer(), nullable=True),
    sa.Column('interceptions_away', sa.Integer(), nullable=True),
    sa.Column('clearances_home', sa.Integer(), nullable=True),
    sa.Column('clearances_away', sa.Integer(), nullable=True),
    sa.Column('additional_stats', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id')
    )
    op.create_index(op.f('ix_match_statistics_id'), 'match_statistics', ['id'], unique=False)
    op.create_table('odds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('bookmaker', sa.String(), nullable=False),
    sa.Column('market', sa.String(), nullable=False),
    sa.Column('home_win', sa.Float(), nullable=True),
    sa.Column('draw', sa.Float(), nullable=True),
    sa.Column('away_win', sa.Float(), nullable=True),
    sa.Column('over_1_5', sa.Float(), nullable=True),
    sa.Column('under_1_5', sa.Float(), nullable=True),
    sa.Column('over_2_5', sa.Float(), nullable=True),
    sa.Column('under_2_5', sa.Float(), nullable=True),
    sa.Column('over_3_5', sa.Float(), nullable=True),
    sa.Column('under_3_5', sa.Float(), nullable=True),
    sa.Column('btts_yes', sa.Float(), nullable=True),
    sa.Column('btts_no', sa.Float(), nullable=True),
    sa.Column('asian_handicap_line', sa.Float(), nullable=True),
    sa.Column('asian_handicap_home', sa.Float(), nullable=True),
    sa.Column('asian_handicap_away', sa.Float(), nullable=True),
    sa.Column('corners_over_8_5', sa.Float(), nullable=True),
    sa.Column('corners_under_8_5', sa.Float(), nullable=True),
    sa.Column('corners_over_9_5', sa.Float(), nullable=True),
    sa.Column('corners_under_9_5', sa.Float(), nullable=True),
    sa.Column('corners_over_10_5', sa.Float(), nullable=True),
    sa.Column('corners_under_10_5', sa.Float(), nullable=True),
    sa.Column('additional_markets', sa.JSON(), nullable=True),
    sa.Column('odds_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_odds_id'), 'odds', ['id'], unique=False)
    op.create_table('player_injuries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('injury_type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('body_part', sa.String(), nullable=True),
    sa.Column('injury_date', sa.Date(), nullable=False),
    sa.Column('expected_return_date', sa.Date(), nullable=True),
    sa.Column('actual_return_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('recovery_percentage', sa.Float(), nullable=True),
    sa.Column('impact_on_team', sa.Float(), nullable=True),
    sa.Column('replacement_quality', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_injuries_id'), 'player_injuries', ['id'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('prediction_type', sa.String(), nullable=False),
    sa.Column('market_type', sa.String(), nullable=False),
    sa.Column('predicted_outcome', sa.String(), nullable=True),
    sa.Column('predicted_probability', sa.Float(), nullable=True),
    sa.Column('recommended_odds', sa.Float(), nullable=True),
    sa.Column('actual_odds', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('value_score', sa.Float(), nullable=True),
    sa.Column('kelly_percentage', sa.Float(), nullable=True),
    sa.Column('form_weight', sa.Float(), nullable=True),
    sa.Column('h2h_weight', sa.Float(), nullable=True),
    sa.Column('xg_weight', sa.Float(), nullable=True),
    sa.Column('injury_impact', sa.Float(), nullable=True),
    sa.Column('weather_impact', sa.Float(), nullable=True),
    sa.Column('motivation_impact', sa.Float(), nullable=True),
    sa.Column('analysis_summary', sa.Text(), nullable=True),
    sa.Column('key_factors', sa.JSON(), nullable=True),
    sa.Column('is_validated', sa.Boolean(), nullable=True),
    sa.Column('validation_score', sa.Float(), nullable=True),
    sa.Column('final_recommendation', sa.String(), nullable=True),
    sa.Column('actual_outcome', sa.String(), nullable=True),
    sa.Column('is_winner', sa.Boolean(), nullable=True),
    sa.Column('profit_loss', sa.Float(), nullable=True),
    sa.Column('predicted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_id'), 'predictions', ['id'], unique=False)
    op.create_table('odds_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('odds_id', sa.Integer(), nullable=False),
    sa.Column('home_win', sa.Float(), nullable=True),
    sa.Column('draw', sa.Float(), nullable=True),
    sa.Column('away_win', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('movement_direction', sa.String(), nullable=True),
    sa.Column('movement_percentage', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['odds_id'], ['odds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_odds_history_id'), 'odds_history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_odds_history_id'), table_name='odds_history')
    op.drop_table('odds_history')
    op.drop_index(op.f('ix_predictions_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_player_injuries_id'), table_name='player_injuries')
    op.drop_table('player_injuries')
    op.drop_index(op.f('ix_odds_id'), table_name='odds')
    op.drop_table('odds')
    op.drop_index(op.f('ix_match_statistics_id'), table_name='match_statistics')
    op.drop_table('match_statistics')
    op.drop_index(op.f('ix_team_statistics_id'), table_name='team_statistics')
    op.drop_table('team_statistics')
    op.drop_index(op.f('ix_players_id'), table_name='players')
    op.drop_index(op.f('ix_players_external_id'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_matches_match_date'), table_name='matches')
    op.drop_index(op.f('ix_matches_league'), table_name='matches')
    op.drop_index(op.f('ix_matches_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_external_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_teams_name'), table_name='teams')
    op.drop_index(op.f('ix_teams_league'), table_name='teams')
    op.drop_index(op.f('ix_teams_id'), table_name='teams')
    op.drop_index(op.f('ix_teams_external_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_bet_combinations_id'), table_name='bet_combinations')
    op.drop_table('bet_combinations')
    # ### end Alembic commands ###